import { Roboto } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/shared/Navbar/Navbar";
import AuthProvider from "@/provider/AuthProvider";
import CartProvider from "@/provider/CartProvider";
import Footer from "@/components/shared/Footer";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Bitss Security Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased font-roboto`}>
        <AuthProvider>
          <CartProvider>
            <Navbar />
            {children}
            <Footer />
            <Toaster />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
