export const CONTENT = {
  en: {
    pageTitle: "BITSS VWAR USB Flash Memory",
    productType: "Self Installation",
    descriptionTitle: "Product Description",
    description: [
      "Bitss USB VWAR is a dedicated USB key malware and virus protection, this Bitss software is downloadable to all types of USB keys.",
      "Protect your USB data, software, documents, files, photos and videos from malware and viruses.",
      "Be safe with Bitss — a powerful next-generation anti-malware solution that keeps your USB drives completely virus-free. Built with AES-based ScanVault security, it actively blocks malware, prevents infection, and stops harmful scripts before they can enter your device.",
      "Even when connected to compromised systems, your USB remains clean and protected. Internal files stay safe, untouched, and fully secure from virus attacks.",
      "With smart plug-and-play activation and real-time protection, VWAR delivers uncompromising USB security — anytime, anywhere.",
    ],
    featuresTitle: "Product Features",
    features: [
      "Fully Secured USB Drive",
      "Build in Anti-Malware File Protection",
      "Smart USB Detection Plug & Play",
      "Life time Free Software Update",
      "Easy Installation on Any USB",
    ],
    downloadTitle: "Download Installation Toolkit",
    downloadBtn: "Download",
    downloadLoading: "Fetching link...",
    downloadError: "Failed to fetch download link. Please try again.",
    selectLicense: "Select Your License",
    colLicense: "License",
    colPrice: "Euro",
    selectPayment: "Payment Method",
    quantity: "Quantity",
    orderTitle: "Order Summary",
    selectedPlan: "Selected Plan:",
    unitPrice: "Unit Price:",
    total: "Total:",
    placeOrder: "Place Order",
    processing: "Processing...",
    noneSelected: "Select a license to see summary",
    terms: "By placing this order you agree to our terms and conditions. We'll contact you within 24-48 hours to confirm.",
    securePayment: "Secure Payment",
    securePaymentDesc: "Your information is safe",
    fastDelivery: "Fast Delivery",
    fastDeliveryDesc: "Worldwide shipping",
    support: "24/7 Support",
    supportDesc: "Here to help anytime",
    price: (lic) => `€${lic.euro.toFixed(2)}`,
    total_price: (lic, qty) => `€${(lic.euro * qty).toFixed(2)}`,
    unit_price: (lic) => `€${lic.euro.toFixed(2)}`,
    name: (lic) => lic.nameEn,
  },
  bn: {
    pageTitle: "বিটস ভিডব্লিউএআর ইউএসবি ফ্ল্যাশ মেমোরি",
    productType: "স্ব-ইনস্টলেশন",
    descriptionTitle: "পণ্যের বিবরণ",
    description: [
      "বিটস ইউএসবি ভিডব্লিউএআর একটি ডেডিকেটেড ইউএসবি কী ম্যালওয়্যার ও ভাইরাস সুরক্ষা সফটওয়্যার, যা সব ধরনের ইউএসবি কীতে ডাউনলোড করা যায়।",
      "আপনার ইউএসবি ডেটা, সফটওয়্যার, ডকুমেন্ট, ফাইল, ছবি এবং ভিডিও ম্যালওয়্যার ও ভাইরাস থেকে সুরক্ষিত রাখুন।",
      "বিটসের সাথে নিরাপদ থাকুন — একটি শক্তিশালী পরবর্তী প্রজন্মের অ্যান্টি-ম্যালওয়্যার সমাধান যা আপনার ইউএসবি ড্রাইভকে সম্পূর্ণ ভাইরাসমুক্ত রাখে। AES-ভিত্তিক স্ক্যানভল্ট সুরক্ষা দিয়ে নির্মিত, এটি সক্রিয়ভাবে ম্যালওয়্যার ব্লক করে এবং ক্ষতিকর স্ক্রিপ্টগুলি আপনার ডিভাইসে প্রবেশের আগেই থামিয়ে দেয়।",
      "এমনকি ক্ষতিগ্রস্ত সিস্টেমের সাথে সংযুক্ত থাকলেও, আপনার ইউএসবি পরিষ্কার এবং সুরক্ষিত থাকে। অভ্যন্তরীণ ফাইলগুলি নিরাপদ এবং ভাইরাস আক্রমণ থেকে সম্পূর্ণ সুরক্ষিত।",
      "স্মার্ট প্লাগ-এন্ড-প্লে অ্যাক্টিভেশন এবং রিয়েল-টাইম সুরক্ষার মাধ্যমে, ভিডব্লিউএআর যেকোনো সময়, যেকোনো জায়গায় আপোসহীন ইউএসবি নিরাপত্তা প্রদান করে।",
    ],
    featuresTitle: "পণ্যের বৈশিষ্ট্য",
    features: [
      "সম্পূর্ণ সুরক্ষিত ইউএসবি ড্রাইভ",
      "বিল্ট-ইন অ্যান্টি-ম্যালওয়্যার ফাইল সুরক্ষা",
      "স্মার্ট ইউএসবি ডিটেকশন প্লাগ অ্যান্ড প্লে",
      "আজীবন বিনামূল্যে সফটওয়্যার আপডেট",
      "যেকোনো ইউএসবিতে সহজ ইনস্টলেশন",
    ],
    downloadTitle: "ইনস্টলেশন টুলকিট ডাউনলোড করুন",
    downloadBtn: "ডাউনলোড",
    downloadLoading: "লিংক আনা হচ্ছে...",
    downloadError: "ডাউনলোড লিংক পাওয়া যায়নি। আবার চেষ্টা করুন।",
    selectLicense: "আপনার লাইসেন্স বেছে নিন",
    colLicense: "লাইসেন্স",
    colPrice: "টাকা",
    selectPayment: "পেমেন্ট পদ্ধতি",
    quantity: "পরিমাণ",
    orderTitle: "অর্ডার সারসংক্ষেপ",
    selectedPlan: "নির্বাচিত প্ল্যান:",
    unitPrice: "একক মূল্য:",
    total: "মোট:",
    placeOrder: "অর্ডার করুন",
    processing: "প্রক্রিয়া করা হচ্ছে...",
    noneSelected: "সারসংক্ষেপ দেখতে লাইসেন্স নির্বাচন করুন",
    terms: "এই অর্ডার দেওয়ার মাধ্যমে আপনি আমাদের শর্তাবলীতে সম্মত হচ্ছেন। আমরা ২৪-৪৮ ঘণ্টার মধ্যে যোগাযোগ করব।",
    securePayment: "নিরাপদ পেমেন্ট",
    securePaymentDesc: "তথ্য সুরক্ষিত",
    fastDelivery: "দ্রুত ডেলিভারি",
    fastDeliveryDesc: "বিশ্বব্যাপী শিপিং",
    support: "২৪/৭ সাপোর্ট",
    supportDesc: "সর্বদা সহায়তায় আছি",
    price: (lic) => `৳${lic.taka.toLocaleString()}`,
    total_price: (lic, qty) => `৳${(lic.taka * qty).toLocaleString()}`,
    unit_price: (lic) => `৳${lic.taka.toLocaleString()}`,
    name: (lic) => lic.nameBn,
  },
};